[[Timers]]
type = "GitHub"
owner = "QuitarHero"
repository = "Hero-Timers"
description = "These are timers by QuitarHero created for Charr's Timer Module."

[[Timers]]
type = "GitHub"
owner = "kittywitch"
repository = "Sabetha-Timers"
description = "This edits the QuitarHero/Hero-Timers Sabetha timers to add the Commander's Markers details back into them, while retaining cardinal directions provided."

[[Pathing]]
type = "Direct"
name = "Teh's Trails Map Completion"
description = "A collection of xTeh.7146's marker packs."
url = "https://github.com/xrandox/TehsTrails/releases/download/v5.2.0/TehsTrails.taco"

[[Pathing]]
type = "Direct"
name = "Teh's Trails Hero Points"
description = "A collection of xTeh.7146's marker packs. This pack contains trails for speed-completing Hero Points either solo or in small groups."
url = "https://github.com/xrandox/TehsTrails-HeroPoints/releases/download/v1.0/TehsTrails-HeroPoints.taco"
